# permissions for end users to view imagebackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagebackup-viewer-role
rules:
- apiGroups:
  - k8slab.io
  resources:
  - imagebackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8slab.io
  resources:
  - imagebackups/status
  verbs:
  - get
